version: '3.8'

services:
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/website
    ports:
      - '8000:8000'
    networks:
      - 'external_network'

networks:
  external_network:
    external: true
    name: eng_api_external_network